on:
    pull_request:
        branches:
        - *
    tags:
    - *
jobs:

    build:
        name: Python ${{ matrix.python-version }} tests on ${{ matrix.os }}
        
        strategy:
            matrix:
                python-version: ["2.7", "3.4", "3.5", "3.6", "3.7"]
                os: ["ubuntu-latest", "macos-latest", "windows-latest"]
                exclude:
                    # The following builds fail with error "Cannot open include file: 'io.h': No such file or directory"
                    # So we just exclude them (for now).
                    - os: windows-latest
                      python-version: "2.7"
                    - os: windows-latest
                      python-version: "3.5"
            fail-fast: false
        runs-on: ${{ matrix.os }}
        
        steps:
        - uses: actions/checkout@master
        - name: Setup python
          uses: actions/setup-python@v1
          with:
              python-version: ${{ matrix.python-version }}
              architecture: x64
        - name: Upgrade requirements
          run: python -m pip install --upgrade pip setuptools twine wheel
        - name: Install pyhyphen
          run: python setup.py develop
        - name: Install pytest
          run: pip install pytest
        - name: Run unit tests
          run: pytest
        - name: Build wheel
          run: python setup.py bdist_wheel
        - name: Upload wheel
          run: twine upload dist/*.whl
          if: github.event_name == 'tags'

